### ISSUE TITLE
Mostrar ús repositori Teacher Tasks

### ISSUE THREAD

**Issue by ssabateAlumne** [IESEBRE/1rASIX_21_22_Teacher_Tasks#8]
Short description:

Ensenyar als alumnes a usar el repo “1rASIX_2021/22_Teacher_Tasks”

Type:
- [ ] Documentation 
- [x] Planification
- [ ] Coding
- [ ] Bug fixing
- [ ] Other...

Estimated achievement date:

28/09/2021

@IESEBRE/equip-10  mireu si està bé

**Comment by ssabate** [comment]
feta
